apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app }}-config
data:
  pegasus-iam.yaml: |
{{- toYaml .Values.configmap | nindent 4 }}
  iam-scheduler.yaml: |
{{- toYaml .Values.scheduler.configmap | nindent 4 }}
