apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-service
  labels:
    app: {{ .Values.app }}
    type: service
spec:
  {{- if .Values.service.enableNodePort }}
  type: NodePort
  {{- end }}
  {{- if .Values.service.externalIPs }}
  externalIPs: {{ .Values.service.externalIPs }}
  {{- end }}
  selector:
    app: {{ .Values.app }}
  ports:
    - name: {{ .Values.app }}-ldap-port
      port: {{ .Values.service.ports.ldap.port }}
      targetPort: {{ .Values.service.ports.ldap.port }}
      {{- if .Values.service.enableNodePort }}
      nodePort: {{ .Values.service.ports.ldap.nodePort }}
      {{- end }}
      protocol: TCP

