apiVersion: v1
kind: Secret
metadata:
  name: slurm-credentials
  namespace: slurm
type: Opaque
stringData:
  mysql-user: slurm
  mysql-password: password
  mysql-root-password: rootpassword
  MYSQL_ROOT_PASSWORD: slurm_root_password
  MYSQL_DATABASE: slurm_acct_db
  MYSQL_USER: slurm
  MYSQL_PASSWORD: password
