apiVersion: v1
kind: Service
metadata:
  name: slurmdbd
  namespace: slurm
spec:
  ports:
    - port: 6819
      targetPort: 6819
  selector:
    app: slurmdbd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurmdbd
  namespace: slurm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slurmdbd
  template:
    metadata:
      labels:
        app: slurmdbd
    spec:
      initContainers:
        # Wait for MySQL to be ready
        - name: wait-for-mysql
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z mysql 3306; do
                echo "Waiting for MySQL to be ready..."
                sleep 2
              done
              dd if=/dev/random of=/etc/slurm/jwt_hs256.key bs=32 count=1
          volumeMounts:
            - name: jwt-pvc
              mountPath: /etc/slurm
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
      hostname: slurmdbd
      containers:
        - name: slurmdbd
          image: slurm-docker-cluster:25.05.3
          imagePullPolicy: IfNotPresent 
          command:
            - sh
            - -c
            - |
              cp /tmp/jwt-pvc/jwt_hs256.key /etc/slurm/
              chown slurm:slurm /etc/slurm/jwt_hs256.key
              chmod 0600 /etc/slurm/jwt_hs256.key
              /usr/local/bin/docker-entrypoint.sh slurmdbd
          ports:
            - containerPort: 6819
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: slurm-credentials
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: slurm-credentials
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: jwt-pvc
              mountPath: /tmp/jwt-pvc
              readOnly: true
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - pidof slurmdbd
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - pidof slurmdbd
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: jwt-pvc
          persistentVolumeClaim:
            claimName: jwt-pvc
