apiVersion: v1
kind: Service
metadata:
  name: slurmctld
  namespace: slurm
spec:
  type: NodePort
  ports:
    - name: slurm
      port: 6817
      targetPort: 6817
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 30022
  selector:
    app: slurmctld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurmctld
  namespace: slurm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slurmctld
  template:
    metadata:
      labels:
        app: slurmctld
    spec:
      initContainers:
        # Wait for slurmdbd to be ready
        - name: wait-for-slurmdbd
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z slurmdbd 6819; do
                echo "Waiting for slurmdbd to be ready..."
                sleep 2
              done
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
      hostname: slurmctld
      containers:
        - name: slurmctld
          image: slurm-docker-cluster:25.05.3
          env:
            - name: SSH_ENABLE
              value: "true"
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              cp /tmp/jwt-pvc/jwt_hs256.key /etc/slurm/
              chown slurm:slurm /etc/slurm/jwt_hs256.key
              chmod 0600 /etc/slurm/jwt_hs256.key
              /usr/local/bin/docker-entrypoint.sh slurmctld                  
          ports:
            - containerPort: 6817
            - containerPort: 22
          workingDir: /data
          securityContext:
            privileged: true
          volumeMounts:
            - name: jobdir
              mountPath: /data
            - name: jwt-pvc
              mountPath: /tmp/jwt-pvc
              readOnly: true
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - scontrol ping
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - scontrol ping
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: jobdir
          persistentVolumeClaim:
            claimName: slurm-jobdir-pvc
        - name: jwt-pvc
          persistentVolumeClaim:
            claimName: jwt-pvc
