apiVersion: v1
kind: Service
metadata:
  name: slurmrestd
  namespace: slurm
spec:
  type: NodePort
  ports:
    - port: 6820
      targetPort: 6820
      nodePort: 30820
  selector:
    app: slurmrestd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurmrestd
  namespace: slurm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slurmrestd
  template:
    metadata:
      labels:
        app: slurmrestd
    spec:
      initContainers:
        # Wait for slurmctld to be ready
        - name: wait-for-slurmctld
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z slurmctld 6817; do
                echo "Waiting for slurmctld to be ready..."
                sleep 2
              done
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
      hostname: slurmrestd
      containers:
        - name: slurmrestd
          image: slurm-docker-cluster:25.05.3
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              cp /tmp/jwt-pvc/jwt_hs256.key /etc/slurm/
              chown slurm:slurm /etc/slurm/jwt_hs256.key
              chmod 0600 /etc/slurm/jwt_hs256.key
              /usr/local/bin/docker-entrypoint.sh slurmrestd                 
          ports:
            - containerPort: 6820
          securityContext:
            privileged: true
          volumeMounts:
            - name: jwt-pvc
              mountPath: /tmp/jwt-pvc
              readOnly: true
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - test -S /var/run/slurmrestd/slurmrestd.socket
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - test -S /var/run/slurmrestd/slurmrestd.socket
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: jwt-pvc
          persistentVolumeClaim:
            claimName: jwt-pvc
