apiVersion: v1
kind: Service
metadata:
  name: c1
  namespace: slurm
spec:
  ports:
    - port: 6818
      targetPort: 6818
  selector:
    node: c1
---
apiVersion: v1
kind: Service
metadata:
  name: c2
  namespace: slurm
spec:
  ports:
    - port: 6818
      targetPort: 6818
  selector:
    node: c2    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurmd-c1
  namespace: slurm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slurmd
      node: c1
  template:
    metadata:
      labels:
        app: slurmd
        node: c1
    spec:
      hostname: c1
      subdomain: compute-nodes
      initContainers:
        # Wait for slurmctld to be ready
        - name: wait-for-slurmctld
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z slurmctld 6817; do
                echo "Waiting for slurmctld to be ready..."
                sleep 2
              done
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
      containers:
        - name: slurmd
          image: slurm-docker-cluster:25.05.3
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              /usr/local/bin/docker-entrypoint.sh slurmd                        
          ports:
            - containerPort: 6818
          securityContext:
            privileged: true
          volumeMounts:
            - name: jobdir
              mountPath: /data
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - pidof slurmd
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - pidof slurmd
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: jobdir
          persistentVolumeClaim:
            claimName: slurm-jobdir-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurmd-c2
  namespace: slurm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slurmd
      node: c2
  template:
    metadata:
      labels:
        app: slurmd
        node: c2
    spec:
      hostname: c2
      subdomain: compute-nodes
      initContainers:
        # Wait for slurmctld to be ready
        - name: wait-for-slurmctld
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z slurmctld 6817; do
                echo "Waiting for slurmctld to be ready..."
                sleep 2
              done
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
      containers:
        - name: slurmd
          image: slurm-docker-cluster:25.05.3
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              /usr/local/bin/docker-entrypoint.sh slurmd             
          ports:
            - containerPort: 6818
          securityContext:
            privileged: true
          volumeMounts:
            - name: jobdir
              mountPath: /data
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - pidof slurmd
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - pidof slurmd
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: jobdir
          persistentVolumeClaim:
            claimName: slurm-jobdir-pvc
