{{- if .Values.mysqldump.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-mysqldump-pv" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
  {{- end }}
spec:
  storageClassName: {{ printf "%s-mysqldump-volume" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.mysqldump.volumePath }}
{{- end }}