apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-service
  labels:
    app: {{ .Values.app }}
    type: service
spec:
  {{- if eq .Values.service.enableNodePort true }}
  type: NodePort
  {{- end }}
  selector:
    app: vps-server
  ports:
    - name: grpc-port
      port: {{ .Values.service.ports.grpc.port }}
      targetPort: {{ .Values.service.ports.grpc.port }}
      {{- if eq .Values.service.enableNodePort true }}
      nodePort:  {{ .Values.service.ports.grpc.nodePort }}
      {{- end }}
      protocol: TCP
    - name: http-port
      port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.port }}
      {{- if eq .Values.service.enableNodePort true }}
      nodePort:  {{ .Values.service.ports.http.nodePort }}
      {{- end }}
      protocol: TCP