apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app }}-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.app }}-data-volume
  resources:
    requests:
      storage: 5Gi
