apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.app }}-data-pv
spec:
  storageClassName: {{ .Values.app }}-data-volume
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  local:
    path: {{ .Values.volume.data_path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: Exists