apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.app }}
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: {{ .Values.redis.app }}