apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.redis.app }}-config
data:
  redis.conf: |
    # Redis High availability with Sentinel on Kubernetes(K8s) configurations
    # -----------------------------------------------------------------------

    bind 0.0.0.0

    # configurations for snaposhot and AOF
    # read more : https://redis.io/docs/manual/persistence/
    dbfilename dump.rdb
    dir /data
    appendonly yes
    appendfilename "appendonly.aof"

    # This is used by the replics nodes to communicate with master to replicate the data.
    # we are using a user called "replication" for this, and the a strong pwd for the same is given in masterauth
    masterauth {{ .Values.redis.password }}
    requirepass {{ .Values.redis.password }}

    # port, each redis nodes will be used
    port 6379