apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sentinel.app }}-service
spec:
  clusterIP: None
  ports:
  - port: 26379
    targetPort: 26379
    name: sentinel
  selector:
    app: {{ .Values.sentinel.app }}
