kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-pvc" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
  {{- end }}
spec:
  storageClassName: {{ template "common.names.fullname" . }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size }}