apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.redis.app }}-pv
spec:
  storageClassName: redis-volume
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.redis.persistentPath }}