apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-pv" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
  {{- end }}
spec:
  storageClassName: {{ template "common.names.fullname" . }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: {{ .Values.nodeAffinityPreset.key}}
          operator: Exists
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.persistence.sharePath }}
