app: virtual-registry-management

images:
  vrm: 10.247.4.4:80/trusted-cloud/virtual-registry-management:0.0.5
  debugger: 10.247.4.4:80/trusted-cloud/debugger:1.0.2
  eventpublishPlugin: 10.247.4.4:80/trusted-cloud/event-publish-plugin:0.1.0
  #filebeat: 10.247.4.4:80/trusted-cloud/filebeat:8.14.3

core:
  enabled: true
  configmap:
    version: 0.0.5
    kind: VirtualRegistryManagement
    VirtualRegistryManagement:
      instance: VirtualRegistryManagement
      developer: true
      http:
        host: 0.0.0.0:8106
      grpc:
        host: 0.0.0.0:5106
        unix_socket: 
          path: /run/VirtualRegistryManagement.sock
          conn_count: 20
      logger:
        system_log:
          path: /var/log/ASUS/
          mode: error
          show_in_console: true
        access_log:
          path: /var/log/ASUS/
        event_consume_log:
          path: /var/log/ASUS/
      tracer:
        enable: false
        host: http://jaeger-service:14268/api/traces
        timeout: 10
      filepath:  # TODO: need update
      # <scheme>://<path> => <root>/<prefix>/<path>/<suffix>
      - name: dss-public
        scheme: dss-public
        type: local
        root: /normal/storage
        prefix: "%s" # project-id
      - name: dss-private
        scheme: dss-private
        type: local
        root: /sensitivity/storage
        prefix: "%s" # project-id
      - name: sss
        scheme: sss
        type: local
        root: /normal/site-storage
        prefix: "%s" # project-id
    storage:
      provider: mariadb
      mariadb:
        host: mariadb-galera:3306
        account: root
        password: ""  # TODO: need update
        name: vrm
        timeout: 5
        max_open_conns: 150
        conn_max_lifetime: 10
        max_idle_conns: 150
    vps:
      host: vps-service:5110
      tls:
        enable: false
        cert_path: /root/server-csr/IAM.pem
      connection_per_host: 3
    authentication:
      service: myiam
    openstack:
      - namespace: public
        service: opstk
      - namespace: private
        service: opstk
    event_consume:
      service: my_redis_sentinel
      channels:
      - FromIAM
    services:
      - name: myiam
        kind: iam
        hosts:
          - iam-service:5051
        tls:
          enable: false
          cert_path: /root/server-csr/IAM.pem
        connection_per_host: 3
      - name: my_redis_sentinel
        kind: redis_sentinel
        hosts:
        - redis-sentinel-service:26379
        password: ""  # TODO: need update
        master_group_name: mymaster
      - name: opstk
        kind: openstack
        identity_endpoint: http://127.0.0.1:5000/v3  # TODO: need update
        username: "" # TODO: need update
        password: "" # TODO: need update
        domain_name: "" # TODO: need update
        admin_project: "" # TODO: need update
        allow_reauth: true
        pid_source: "" # TODO: need update
    event_publish:
      plugins:
      - name: EventPublishPlugin
        type: grpc
        binary_path: "/var/lib/ASUS/vrm/eventpublish/eventpublishplugin"
        config_path: "/var/lib/ASUS/vrm/eventpublish/config/eventpublishplugin.yaml"
        socket_path: /run/eventpublishplugin.sock
        start_cmd_args:
          --redis-channel: FromVRM

scheduler:
  enabled: true
  configmap:
    version: 0.0.2-addb72a
    kind: VirtualRegistryManagementScheduler
    VirtualRegistryManagementScheduler:
      instance: VirtualRegistryManagementScheduler
      core_grpc:
        hosts: ["virtual-registry-management-core-service:5106"]
        tls:
          enable: true ####
          cert_path: /root/server-csr/VRM.pem
        connection_per_host: 3
    event_consume:
      service: my_redis_sentinel
      channels:
      - FromIAM

eventpublish:
  eventpublishPlugin:
    plugin:
      name: EventPublishPlugin
      instance: VirtualRegistryManagement-EventPublishPlugin
      version: 0.1.0
      socket_path: "/run/eventpublishplugin.sock"
      logger:
        system_log:
          path: /var/log/ASUS
          max_size: 10
          max_backups: 5
          max_age: 10
          compress: false
          mode: debug
          show_in_console: true
        event_log:
          path: /var/log/ASUS
          max_size: 10
          max_backups: 5
          max_age: 10
      tracer:
        enable: false
        collector_endpoint: http://jaeger-service:14268/api/traces
        timeout: 10
      service: my_redis_sentinel
      services:
      - name: my_redis_sentinel
        kind: redis_sentinel
        hosts:
        - redis-sentinel-service:26379
        password: "" # TODO: need update
        master_group_name: mymaster

service:
  core:
    enableNodePort: false
    externalIPs: []
    grpc:
      port: 5106
      nodePort: 31106
    http:
      port: 8106
      nodePort: 32106

volume: # TODO: need update
  dss_private_path: "/sensitivity/storage"
  dss_public_path: "/normal/storage"
  sss_path: "/normal/site-storage"

serviceMonitor:
  enable: false

elasticSearch:
  hosts: [""] # TODO: need update
  index: accesslog-%{[service.name]}
  protocol: "https"
  pipeline: virtualregistrymanagement-pipeline
  preset: balanced
  username: "elastic" # TODO: need update
  password: "" # TODO: need update
  ssl:
    enabled: false
    verification_mode: none
