apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  {{- if eq .Values.volume.type "local" }}
  storageClassName: {{ .Values.app }}-local-volume
  {{- else }}
  storageClassName: {{ .Values.app }}-nfs-volume
  {{- end }}
  resources:
    requests:
      storage: 5Gi
